name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install MkDocs
      run: pip install mkdocs

    - name: Build MkDocs site
      run: mkdocs build

    - name: Deploy to Linode
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.LINODE_IP }}
        username: gh_action
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ''
        script: |
          cd /code/auto-doc-practice
          git pull origin main
          poetry shell
          mkdocs build
          cp -r site /web
