# name: Release and Publish

# on:
#   workflow_dispatch:

# jobs:
#   create_release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Create GitHub Release
#         id: create_release
#         uses: actions/create-release@v1
#         with:
#           tag_name: ${{ github.ref_name }}
#           release_name: "Release ${{ github.ref_name }}"
#           body: "Release for version ${{ github.ref_name }}"
#           draft: false
#           prerelease: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
